# Generated by Django 5.1.3 on 2025-05-11 10:26

import STT.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STT", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FineTuningJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("dataset_path", models.CharField(max_length=255)),
                ("base_model", models.CharField(default="base", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_path", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="audiorecording",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to=STT.models.random_name
            ),
        ),
    ]
